### ISSUE TITLE
update of icingaweb/icingaweb-php-library causes Exception

### ISSUE THREAD

**Issue by tectumopticum** [Thomas-Gelf/icingaweb2-module-eventtracker#81]
After upgrade from icingaweb2 2.13.x to 2.14.0 and the icingaweb-php-library to. 1.0.0 the eventtracker-daemon doesn't start anymore:
```
systemctl status icinga-eventtracker.service
● icinga-eventtracker.service - Icinga Eventtracker Daemon
     Loaded: loaded (/etc/systemd/system/icinga-eventtracker.service; enabled; preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2026-07-20 08:34:26 CEST; 1s ago
       Docs: https://github.com/Thomas-Gelf/icingaweb2-module-eventtracker
    Process: 18160 ExecStart=/usr/bin/icingacli eventtracker daemon run (code=exited, status=255/EXCEPTION)
   Main PID: 18160 (code=exited, status=255/EXCEPTION)
     Status: "ready"
        CPU: 74ms

░░ A start job for unit icinga-eventtracker.service has finished successfully.
░░
░░ The job identifier is 42636.
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function React\Promise\resolve(), 0 passed in /usr/share/icingaweb2/>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: Stack trace:
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #0 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/DaemonDb.php(274): React\Promise\resolve()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #1 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/DaemonDb.php(100): Icinga\Module\Eventtracker\Daemon\DaemonDb->
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #2 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/BackgroundDaemon.php(124): Icinga\Module\Eventtracker\Daemon\D>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #3 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/BackgroundDaemon.php(86): Icinga\Module\Eventtracker\Daemon\Ba>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #4 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Eventtracker\Daemon\BackgroundDaemo>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #5 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/StreamSelectLoop.php(183): React\EventLoop\Tick\FutureTickQueue->tick()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #6 /usr/share/icingaweb2/modules/eventtracker/application/clicommands/DaemonCommand.php(19): React\EventLoop\StreamSelectLoop->run()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #7 /usr/share/php/Icinga/Cli/Loader.php(271): Icinga\Module\Eventtracker\Clicommands\DaemonCommand->runAction()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #8 /usr/share/php/Icinga/Application/Cli.php(167): Icinga\Cli\Loader->dispatch()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #9 /usr/share/php/Icinga/Application/Cli.php(157): Icinga\Application\Cli->dispatchOnce()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #10 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #11 {main}
Jul 20 08:38:58 icingaweb2 eventtracker[17813]:   thrown in /usr/share/icinga-php/vendor/vendor/react/promise/src/functions.php on line 24
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: Fatal error: Uncaught ArgumentCountError: Too few arguments to function React\Promise\resolve(), 0 passed in /usr/share/icingaweb2/modul>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: Stack trace:
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #0 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/DaemonDb.php(274): React\Promise\resolve()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #1 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/DaemonDb.php(100): Icinga\Module\Eventtracker\Daemon\DaemonDb->
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #2 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/BackgroundDaemon.php(124): Icinga\Module\Eventtracker\Daemon\D>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #3 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/BackgroundDaemon.php(86): Icinga\Module\Eventtracker\Daemon\Ba>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #4 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Eventtracker\Daemon\BackgroundDaemo>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #5 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/StreamSelectLoop.php(183): React\EventLoop\Tick\FutureTickQueue->tick()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #6 /usr/share/icingaweb2/modules/eventtracker/application/clicommands/DaemonCommand.php(19): React\EventLoop\StreamSelectLoop->run()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #7 /usr/share/php/Icinga/Cli/Loader.php(271): Icinga\Module\Eventtracker\Clicommands\DaemonCommand->runAction()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #8 /usr/share/php/Icinga/Application/Cli.php(167): Icinga\Cli\Loader->dispatch()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #9 /usr/share/php/Icinga/Application/Cli.php(157): Icinga\Application\Cli->dispatchOnce()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #10 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #11 {main}
Jul 20 08:38:58 icingaweb2 eventtracker[17813]:   thrown in /usr/share/icinga-php/vendor/vendor/react/promise/src/functions.php on line 24
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: PHP Fatal error:  Uncaught TypeError: Icinga\Module\Eventtracker\Daemon\JobRunner::stopDb(): Return value must be of type React\Promise\>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: Stack trace:
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #0 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/JobRunner.php(221): Icinga\Module\Eventtracker\Daemon\JobRunne>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #1 [internal function]: Icinga\Module\Eventtracker\Daemon\JobRunner->__destruct()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #2 {main}
Jul 20 08:38:58 icingaweb2 eventtracker[17813]:   thrown in /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/JobRunner.php on line 129
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: Fatal error: Uncaught TypeError: Icinga\Module\Eventtracker\Daemon\JobRunner::stopDb(): Return value must be of type React\Promise\Exten>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: Stack trace:
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #0 /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/JobRunner.php(221): Icinga\Module\Eventtracker\Daemon\JobRunne>
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #1 [internal function]: Icinga\Module\Eventtracker\Daemon\JobRunner->__destruct()
Jul 20 08:38:58 icingaweb2 eventtracker[17813]: #2 {main}
Jul 20 08:38:58 icingaweb2 eventtracker[17813]:   thrown in /usr/share/icingaweb2/modules/eventtracker/library/Eventtracker/Daemon/JobRunner.php on line 129
Jul 20 08:38:58 icingaweb2 systemd[1]: icinga-eventtracker.service: Main process exited, code=exited, status=255/EXCEPTION
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ An ExecStart= process belonging to unit icinga-eventtracker.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 255.
Jul 20 08:38:58 icingaweb2 systemd[1]: icinga-eventtracker.service: Failed with result 'exit-code'.

Icingaweb2:    2.14.0
PHP:               8.3.31

icinga/icinga-php-thirdparty 	1.0.0 
icinga/icinga-php-library 	1.0.0 
icinga/icinga-php-legacy 	1.1.0


MODULE         VERSION   STATE     DESCRIPTION
businessprocess 2.5.1     enabled   A Business Process viewer and modeler
clustergraph   1.0.8     enabled   Visual representation of Icinga Clusters
company        1.0.0     enabled   Company Theme example
cube           1.3.3     enabled   Cube for Icinga Web
dependencies   1.0.3     enabled   Icinga Dependency Views
director       1.11.9    enabled   Director - Config tool for Icinga 2
eventtracker   0.9.0     enabled   Operator Dashboard to track Incidents from various sources
fileshipper    1.2.0     enabled   Fileshipper for Icinga Director
grafana        3.1.1     enabled   Grafana - A perfdata visualisation module
icingadb       1.4.0     enabled   Icinga DB Web
iet            0.9.0     enabled   iET module for Icinga Web 2
incubator      0.23.0    enabled   Incubator provides bleeding-edge libraries
map            2.0.0     enabled   Map - Visualize your hosts and service status
migrate        2.13.0    enabled   Migrate module
mistapiimport  0.1.3     enabled   Director Import for MIST API
pdfexport      0.11.0    enabled   PDF Export via Google Chrome/Chromium
prime          1.0.0     enabled   ImportSource for Cisco Prime Infrastructure
reporting      1.0.3     enabled   Reporting
vspheredb      1.8.4     enabled   Icinga vSphere® Integration
x509           1.3.2     enabled   Scan and view X.509 certificate usage
```
